spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    placeholders:
      rag_embedding_dimensions: ${RAG_EMBEDDING_DIMENSIONS}
