spring:
  config:
    import: optional:file:../.env[.properties]
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/projectx_local}
    username: ${SPRING_DATASOURCE_USERNAME:projectx}
    password: ${SPRING_DATASOURCE_PASSWORD:projectx}
